project:
  type: website

website:
  title: "Rob McDonnell:Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: united
    css: styles.css

editor: source
drafts:
  - drafts/*.qmd
draft-mode: gone 
execute: 
  eval: false
freeze: true