---
title: "UK Elections 2019"
date: "2019-12-13"
output: 
  html_document:
    keep_md: true
---

After the UK elections in 2017, I posted about how [easy it was to plot the results in R](https://www.robertmylesmcdonnell.com/content/posts/uk-elections-2017/). Given that the UK just had another election, I thought I'd update that post with another one showing how easy it is to plot these results in R.

```{r message = FALSE, warning=FALSE}
xfun::pkg_attach(c("jsonlite", "dplyr", "rnaturalearthhires", "sf", "parlitools", "ggplot2", "patchwork", "magick"))

res_file <- "https://raw.githubusercontent.com/RobertMyles/blogdata/master/results.json"
uk <- west_hex_map %>% 
  select(ons = gss_code, geometry)

results <- fromJSON(res_file) %>% 
  as_tibble() %>% 
  full_join(uk) %>% 
  select(-candidates) %>% 
  st_as_sf() %>% 
  mutate(
    party = case_when(
      winningParty %in% c("Speaker", "Green", "Alliance", "PC", "SDLP") ~ "Other",
      TRUE ~ winningParty
    )
  ) %>% 
  filter(!is.na(party))

ggplot(results) +
  geom_sf(aes(fill = party), size = 0.2) +
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.title.position = "plot") +
  guides(fill = guide_legend(title = "Party")) +
  scale_fill_manual(values = c("#0084c6", "#880105", "#c70000", 
                               "#ee6f00", "#888888", "#236925",
                               "#ffe500")) +
  ggtitle("UK Elections 2019")
```

Overwhelming rejection of Corbyn's socialism, there. 


```{r}

first <- ggplot(results) +
  geom_sf(aes(fill = sittingParty), size = 0.2) +
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.caption = element_text(hjust = 0.5)) +
  guides(fill = guide_legend(title = "Party")) +
  scale_fill_manual(values = c("#92B4F4", "#0084c6", "#880105",  "forestgreen",
                               "grey88", "#c70000", "darkorange", "#BDF7B7",
                              "#749C75", "#ffe500", "#CEBACF")) +
  labs(caption = "UK Elections 2017")

second <- ggplot(results) +
  geom_sf(aes(fill = winningParty), size = 0.2) +
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.caption = element_text(hjust = 0.5)) +
  guides(fill = guide_legend(title = "Party")) +
  scale_fill_manual(values = c("#92B4F4", "#0084c6", "#880105",  "forestgreen",
                               "#c70000", "darkorange", "#BDF7B7",
                               "#CEBACF",  "#749C75", "#ffe500", "grey88")) +
  labs(caption = "UK Elections 2019")

first + second + plot_annotation(title =  "Comparison of Results, UK elections 2017 & 2019")
```

```{r}
ggplot(results) +
  geom_sf(aes(fill = sittingParty), size = 0.2) +
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.caption = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_fill_manual(values = c("#92B4F4", "#0084c6", "#880105",  "forestgreen",
                               "grey88", "#c70000", "darkorange", "#BDF7B7",
                              "#749C75", "#ffe500", "#CEBACF"))
```

```{r}
ggplot(results) +
  geom_sf(aes(fill = winningParty), size = 0.2) +
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.caption = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_fill_manual(values = c("#92B4F4", "#0084c6", "#880105",  "forestgreen",
                               "#c70000", "darkorange", "#BDF7B7",
                               "#CEBACF",  "#749C75", "#ffe500", "grey88"))
```

```{r}
img1 <- image_read("/Users/f64k1s8/Documents/site/src/content/posts/images/img2019.png")
img2 <- image_read("/Users/f64k1s8/Documents/site/src/content/posts/images/img2017.png")
frames <- image_morph(c(img1, img2, img1), frames = 25)
image_animate(frames, fps = 10)
```

Done with:
```{r}
sessioninfo::session_info()
```


